### ISSUE TITLE
Crashed my express server.

### ISSUE THREAD

**Issue by DavidWalley** [auth0/node-oauth2-jwt-bearer#136]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/node-oauth2-jwt-bearer/tree/main/packages/express-oauth2-jwt-bearer#readme) and [Examples](https://github.com/auth0/node-oauth2-jwt-bearer/blob/main/packages/express-oauth2-jwt-bearer/EXAMPLES.md), and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/node-oauth2-jwt-bearer/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I made a mistake in my client's authentication code, and it crashed my server.

### Reproduction

I have been running a development express server without any problem for some time. I made an error in the client, which I have fixed. But, I was able to crash the express server. I don't want this, or any error, to crash the server, I just want an error message, or rejected request. I don't know where to start with this error:
InvalidTokenError: Invalid Compact JWS
    at /home/dave/Desktop/AAA/PrizeKick/App/api3/node_modules/express-oauth2-jwt-bearer/dist/index.js:300:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/dave/Desktop/AAA/PrizeKick/App/api3/node_modules/express-oauth2-jwt-bearer/dist/index.js:403:24

Obviously I am doing something wrong but the server crashed and I don't want someone else to crash the server.

### express-oauth2-jwt-bearer version

1.6.0

### Node.js version

v20.10.0

**Comment by carluis321** [comment]
@DavidWalley did you create the middleware for catching errors?

**Comment by ehaynes99** [comment]
There's nothing particularly unique about this middleware vs others. You should always have a global "catch all" error handler attached to your app AFTER all other routes and middleware. Note that express looks at the number of arguments to determine if a handler is an error handler or not, so even if unused, it has to have 4.

```typescript
const errorHandler: ErrorRequestHandler = (err, req, res, _next) => {
  console.error('Unhandled error during request', err)
  res.set('Content-Type', 'application/json').status(500).json({ error: err.message })
}

// very last `use`
app.use(errorHandler)
```
